### ISSUE TITLE
When running learn in command line getting: "Did you mean?  LearnTest::Dependencies::SeleniumDriver"

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/fe-code-along-4#18]
Full error: 
```
/Users/Brendan/.rvm/gems/ruby-2.3.1/gems/learn-test-2.5.0/lib/learn_test/strategies/green_onion.rb:25:in `check_dependencies': uninitialized constant LearnTest::Dependencies::SeleniumServer (NameError)

Did you mean?  LearnTest::Dependencies::SeleniumDriver
	from /Users/Brendan/.rvm/gems/ruby-2.3.1/gems/learn-test-2.5.0/lib/learn_test/runner.rb:14:in `run'
	from /Users/Brendan/.rvm/gems/ruby-2.3.1/gems/learn-test-2.5.0/bin/learn-test:64:in `<top (required)>'
	from /Users/Brendan/.rvm/gems/ruby-2.3.1/bin/learn-test:23:in `load'
	from /Users/Brendan/.rvm/gems/ruby-2.3.1/bin/learn-test:23:in `<main>'
	from /Users/Brendan/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Brendan/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jmburges** [comment]
Thanks for the catch! we fixed the issue

**Comment by jmburges** [comment]
Thanks for the catch! we fixed the issue
